### PR TITLE
Find command and some refactor

### PR DESCRIPTION
**Pull request by CasvalDOT**
Adding Find command for show details about a host. 
Change strategy to include host files in the ssh configuration

### CODE REVIEW

**Comment by CasvalDOT** [comment]
@valentinocossar I've created the **find** command; now launching `hssh f` the fzf menu appear and after selecting a connection you will see the details about it. Maybe the output can be improved adding colors and spaces.

I also change the Include strategy for ssh connections

**Comment by CasvalDOT** [comment]
I've added the output of find command more pretty and colorful

**Comment by valentinocossar** [comment]
@CasvalDOT thank you! Some small improvements:
1. Remove empty line on top of the default config template.
2. Make some warning/info messages go to a new line or add space between them and add a final full stop to the message (see screenshot).
3. Add warning message to run `sync` command if `config.hssh.d` folder doesn't exist or is empty.
4. Create `.config/hssh/config.yml` and `.ssh/config` files if don't exist on every command and create `config.hssh.d` folder and add include inside `.ssh/config` file on `sync` command.

text

**Comment by CasvalDOT** [comment]
I added that the system performs a first synchronization if the folder is empty.
I've also add full stop for each message.
Finally the empty line at top of config.yml has been fixed.

**Pull request merged**
